package cc.nkbr.lanzouplus;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.net.Uri;
import android.annotation.SuppressLint;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.webkit.*;
import android.widget.*;
import android.window.*;
import org.json.*;
import java.net.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class LanzouWebActivity extends Activity{
    static final String EXTRA_URL="u",EXTRA_CHALLENGE="challenge",EXTRA_VERIFICATION_URL="verification_url",EXTRA_VERIFICATION_COOKIE="verification_cookie",PREFS="web-browser-v2",HISTORY="history",FAVORITES="favorites",SEARCH_HISTORY="search_queries"; static final int FILE_PICK=401,MAX_HISTORY=120,MAX_SEARCH_HISTORY=30;

    WebView web;EditText address,suggestionInput;TextView title;ImageView siteIcon;ProgressBar progress;FrameLayout shell,noticeLayer,suggestionLayer,contextLayer;LinearLayout suggestionResults;PopupWindow menuPopup;String currentUrl="",currentTitle="";int BG,SURFACE,TEXT,MUTED,DIV,PRIMARY,topInset,bottomInset;float lastTouchX,lastTouchY;ValueCallback<Uri[]> fileCallback;boolean syncingSuggestionInput,challengeMode,verificationFinishing;

    final ExecutorService webIo=Executors.newSingleThreadExecutor();final ArrayList<Entry> history=new ArrayList<>(),favorites=new ArrayList<>();final ArrayList<String> searchQueries=new ArrayList<>();int suggestionGeneration;


  @SuppressLint("SetJavaScriptEnabled")
    public void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING);applyPalette();loadState();challengeMode=getIntent()!=null&&getIntent().getBooleanExtra(EXTRA_CHALLENGE,false);if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);

    shell=new FrameLayout(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);shell.addView(root,new FrameLayout.LayoutParams(-1,-1));noticeLayer=new FrameLayout(this);shell.addView(noticeLayer,new FrameLayout.LayoutParams(-1,-1));suggestionLayer=new FrameLayout(this);suggestionLayer.setVisibility(View.GONE);shell.addView(suggestionLayer,suggestionParams());contextLayer=new FrameLayout(this);contextLayer.setVisibility(View.GONE);shell.addView(contextLayer,new FrameLayout.LayoutParams(-1,-1));
        if(Build.VERSION.SDK_INT>=20)shell.setOnApplyWindowInsetsListener((v,insets)->{topInset=insets.getSystemWindowInsetTop();bottomInset=insets.getSystemWindowInsetBottom();root.setPadding(0,topInset,0,bottomInset);if(suggestionLayer!=null)suggestionLayer.setLayoutParams(suggestionParams());return insets;});

    root.addView(buildToolbar(),new LinearLayout.LayoutParams(-1,toolbarHeight()));progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(View.GONE);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(2)));
        web=new WebView(this);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setLoadWithOverviewMode(true);settings.setUseWideViewPort(true);settings.setBuiltInZoomControls(true);settings.setDisplayZoomControls(false);settings.setSupportMultipleWindows(false);settings.setAllowFileAccess(true);if(challengeMode)settings.setUserAgentString(LanzouCore.verificationUserAgent());android.webkit.CookieManager cookieManager=android.webkit.CookieManager.getInstance();cookieManager.setAcceptCookie(true);if(Build.VERSION.SDK_INT>=21)cookieManager.setAcceptThirdPartyCookies(web,true);

    web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return handleNavigation(v,u);}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return r!=null&&r.isForMainFrame()&&handleNavigation(v,r.getUrl()==null?"":r.getUrl().toString());}@Override public void onPageStarted(WebView v,String u,Bitmap favicon){currentUrl=u==null?"":u;setAddress(currentUrl,false);progress.setVisibility(View.VISIBLE);progress.setProgress(5);}@Override public void onPageFinished(WebView v,String u){currentUrl=u==null?"":u;currentTitle=cleanTitle(v.getTitle(),currentUrl);title.setText(currentTitle);setAddress(currentUrl,false);if(!challengeMode)pushHistory(currentTitle,currentUrl);progress.setVisibility(View.GONE);if(challengeMode)maybeFinishVerificationAfterPage();}});
    web.setWebChromeClient(new WebChromeClient(){@Override public void onReceivedIcon(WebView view,Bitmap icon){if(icon!=null&&siteIcon!=null)siteIcon.setImageBitmap(icon);}@Override public void onProgressChanged(WebView view,int value){progress.setProgress(value);progress.setVisibility(value>=100?View.GONE:View.VISIBLE);}@Override public boolean onShowFileChooser(WebView view,ValueCallback<Uri[]> callback,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=callback;try{Intent i=params==null?new Intent(Intent.ACTION_OPEN_DOCUMENT):params.createIntent();i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,FILE_PICK);return true;}catch(Exception error){fileCallback=null;notice("无法打开系统文件选择器",true);return false;}}});
    web.setDownloadListener((u,ua,d,m,z)->download(u,d,m,z));web.setOnTouchListener((v,e)->{lastTouchX=e.getRawX();lastTouchY=e.getRawY();return false;});web.setOnLongClickListener(v->{showHitMenu();return true;});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));root.addView(buildAddressBar(),new LinearLayout.LayoutParams(-1,addressBarHeight()));setContentView(shell);load(getIntent().getStringExtra(EXTRA_URL));
  }

  int toolbarHeight(){return dp(42);}
  int addressBarHeight(){return dp(42);}
  View buildToolbar(){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(4),dp(1),dp(2),dp(1));bar.setBackgroundColor(SURFACE);TextView back=tool("‹",25);back.setOnClickListener(v->handleBack());bar.addView(back,new LinearLayout.LayoutParams(dp(38),dp(40)));
    siteIcon=new ImageView(this);siteIcon.setImageResource(android.R.drawable.ic_menu_compass);siteIcon.setScaleType(ImageView.ScaleType.CENTER_CROP);bar.addView(siteIcon,new LinearLayout.LayoutParams(dp(24),dp(24)));title=new TextView(this);title.setTextColor(TEXT);title.setTextSize(12);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.MARQUEE);title.setMarqueeRepeatLimit(-1);title.setSelected(true);title.setGravity(Gravity.CENTER_VERTICAL);title.setPadding(dp(5),0,dp(4),0);bar.addView(title,new LinearLayout.LayoutParams(0,dp(40),1));
    TextView fav=tool("☆",20);fav.setContentDescription("收藏当前网页");fav.setOnClickListener(v->favoriteCurrent());bar.addView(fav,new LinearLayout.LayoutParams(dp(38),dp(40)));TextView historyButton=tool("◴",20);historyButton.setContentDescription("浏览历史");historyButton.setOnClickListener(v->showHistoryDialog());bar.addView(historyButton,new LinearLayout.LayoutParams(dp(38),dp(40)));if(challengeMode){TextView done=tool("完成",13);done.setContentDescription("完成验证并继续解析");done.setOnClickListener(v->checkVerificationCompletion(true));bar.addView(done,new LinearLayout.LayoutParams(dp(52),dp(40)));}TextView menu=tool("⋮",23);menu.setContentDescription("网页菜单");menu.setOnClickListener(v->menu(menu));bar.addView(menu,new LinearLayout.LayoutParams(dp(38),dp(40)));return bar;}
    View buildAddressBar(){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(6),dp(2),dp(4),dp(2));bar.setBackgroundColor(SURFACE);address=new EditText(this);address.setSingleLine(true);address.setHorizontallyScrolling(true);address.setTextColor(TEXT);address.setHintTextColor(MUTED);address.setTextSize(12);address.setHint("输入链接或 Bing 搜索");address.setPadding(dp(10),0,dp(10),0);address.setBackground(addressBackground(false));address.setImeOptions(EditorInfo.IME_ACTION_GO|EditorInfo.IME_FLAG_NO_EXTRACT_UI);address.setSelectAllOnFocus(false);bar.addView(address,new LinearLayout.LayoutParams(0,dp(38),1));TextView go=tool("↗",18);go.setContentDescription("打开链接或搜索");go.setOnClickListener(v->navigateInput(address.getText().toString()));bar.addView(go,new LinearLayout.LayoutParams(dp(36),dp(38)));
    address.setOnFocusChangeListener((v,focused)->{address.setBackground(addressBackground(focused));if(focused)address.post(this::openSuggestionIndex);});address.setOnClickListener(v->openSuggestionIndex());address.setOnEditorActionListener((v,action,event)->{if(action==EditorInfo.IME_ACTION_GO||(event!=null&&event.getKeyCode()==KeyEvent.KEYCODE_ENTER)){navigateInput(address.getText().toString());return true;}return false;});return bar;}

  Drawable addressBackground(boolean focused){GradientDrawable g=shape(focused?Color.argb(18,Color.red(PRIMARY),Color.green(PRIMARY),Color.blue(PRIMARY)):Color.TRANSPARENT,15);g.setStroke(dp(focused?2:1),focused?PRIMARY:DIV);return g;}
      FrameLayout.LayoutParams suggestionParams(){return new FrameLayout.LayoutParams(-1,-1,Gravity.FILL);}
  boolean motionEnabled(){try{return android.provider.Settings.Global.getFloat(getContentResolver(),android.provider.Settings.Global.ANIMATOR_DURATION_SCALE,1f)!=0f;}catch(Exception ignored){return true;}}
  void openSuggestionIndex(){if(address==null||suggestionLayer==null)return;if(suggestionLayer.getVisibility()==View.VISIBLE&&suggestionInput!=null){suggestionInput.requestFocus();return;}final String initial=address.getText()==null?"":address.getText().toString();suggestionGeneration++;suggestionLayer.animate().cancel();suggestionLayer.setAlpha(1f);suggestionLayer.setTranslationY(0f);suggestionLayer.removeAllViews();LinearLayout screen=new LinearLayout(this);screen.setOrientation(LinearLayout.VERTICAL);screen.setBackgroundColor(SURFACE);screen.setPadding(0,topInset,0,bottomInset);
                    LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(16),0,dp(16),0);TextView heading=text("索引",20,TEXT);heading.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);heading.setContentDescription("链接与搜索索引，返回键关闭");header.addView(heading,new LinearLayout.LayoutParams(-1,dp(52)));screen.addView(header,new LinearLayout.LayoutParams(-1,dp(52)));



    suggestionInput=new EditText(this);suggestionInput.setSingleLine(false);suggestionInput.setMaxLines(2);suggestionInput.setHorizontallyScrolling(false);suggestionInput.setTextColor(TEXT);suggestionInput.setHintTextColor(MUTED);suggestionInput.setTextSize(15);suggestionInput.setHint("输入链接或搜索内容");suggestionInput.setPadding(dp(14),0,dp(14),0);suggestionInput.setBackground(addressBackground(true));suggestionInput.setImeOptions(EditorInfo.IME_ACTION_GO|EditorInfo.IME_FLAG_NO_EXTRACT_UI);LinearLayout.LayoutParams inputParams=new LinearLayout.LayoutParams(-1,dp(48));inputParams.setMargins(dp(12),0,dp(12),dp(8));screen.addView(suggestionInput,inputParams);
    ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);suggestionResults=new LinearLayout(this);suggestionResults.setOrientation(LinearLayout.VERTICAL);suggestionResults.setPadding(dp(8),dp(2),dp(8),dp(24));scroll.addView(suggestionResults,new ScrollView.LayoutParams(-1,-2));screen.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));suggestionLayer.addView(screen,new FrameLayout.LayoutParams(-1,-1));suggestionLayer.setVisibility(View.VISIBLE);suggestionLayer.bringToFront();
    suggestionInput.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(syncingSuggestionInput)return;String value=s==null?"":s.toString();syncingSuggestionInput=true;address.setText(value);address.setSelection(address.length());syncingSuggestionInput=false;updateSuggestions(value);}public void afterTextChanged(android.text.Editable e){}});suggestionInput.setOnEditorActionListener((v,action,event)->{if(action==EditorInfo.IME_ACTION_GO||(event!=null&&event.getKeyCode()==KeyEvent.KEYCODE_ENTER)){navigateInput(suggestionInput.getText().toString());return true;}return false;});suggestionInput.setText(initial);suggestionInput.setSelection(0,suggestionInput.length());address.clearFocus();suggestionInput.requestFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(suggestionInput,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);updateSuggestions(initial);if(motionEnabled()){screen.setAlpha(0f);screen.setTranslationY(dp(18));screen.animate().alpha(1f).translationY(0f).setDuration(180).setInterpolator(new android.view.animation.DecelerateInterpolator()).start();}}

    void updateSuggestions(String raw){if(suggestionLayer==null||suggestionLayer.getVisibility()!=View.VISIBLE||suggestionResults==null)return;final int generation=++suggestionGeneration;String query=raw==null?"":raw.trim();ArrayList<String> queries=matchingQueries(query,6);ArrayList<Entry> recent=matching(history,query,4),fav=matching(favorites,query,4);renderSuggestions(generation,query,queries,recent,fav,Collections.emptyList());if(query.isEmpty())return;webIo.execute(()->{List<String> bing=fetchBingSuggestions(query);runOnUiThread(()->{if(generation==suggestionGeneration&&suggestionLayer.getVisibility()==View.VISIBLE)renderSuggestions(generation,query,queries,recent,fav,bing);});});}

    ArrayList<Entry> matching(List<Entry> source,String query,int limit){String key=query.toLowerCase(Locale.ROOT);ArrayList<Entry> out=new ArrayList<>();for(Entry e:source){if(key.isEmpty()||(e.title+" "+e.url).toLowerCase(Locale.ROOT).contains(key)){out.add(e);if(out.size()>=limit)break;}}return out;}
  ArrayList<String> matchingQueries(String query,int limit){String key=query.toLowerCase(Locale.ROOT);ArrayList<String> out=new ArrayList<>();for(String value:searchQueries){if(key.isEmpty()||value.toLowerCase(Locale.ROOT).contains(key)){out.add(value);if(out.size()>=limit)break;}}return out;}
  void addSuggestionHeader(String label){TextView header=text(label,12,MUTED);header.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);header.setPadding(dp(12),dp(8),dp(12),0);suggestionResults.addView(header,new LinearLayout.LayoutParams(-1,dp(36)));}
  void addSuggestionRow(View row){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(2));suggestionResults.addView(row,p);}

    void renderSuggestions(int generation,String query,List<String> queries,List<Entry> recent,List<Entry> fav,List<String> bing){if(generation!=suggestionGeneration||suggestionResults==null||suggestionLayer.getVisibility()!=View.VISIBLE)return;suggestionResults.removeAllViews();int rows=0;if(!queries.isEmpty()){addSuggestionHeader("历史搜索");for(String value:queries){String target=value;addSuggestionRow(suggestionRow(value,"再次搜索",()->navigateInput(target)));rows++;}}if(!recent.isEmpty()){addSuggestionHeader("最近浏览");for(Entry e:recent){Entry target=e;addSuggestionRow(suggestionRow(e.title,e.url,()->navigateInput(target.url)));rows++;}}if(!fav.isEmpty()){addSuggestionHeader("收藏");for(Entry e:fav){Entry target=e;addSuggestionRow(suggestionRow(e.title,e.url,()->navigateInput(target.url)));rows++;}}if(!bing.isEmpty()){addSuggestionHeader("Bing 建议");int count=0;for(String s:bing){if(count++>=8)break;String target=s;addSuggestionRow(suggestionRow(s,"搜索建议",()->navigateInput(target)));rows++;}}if(rows==0){String label=query.isEmpty()?"输入关键词、网址或域名":"使用 Bing 搜索："+query;addSuggestionRow(suggestionRow(label,query.isEmpty()?"历史搜索会保留在这里":"按回车立即搜索",()->navigateInput(query)));}}
  View suggestionRow(String main,String sub,Runnable action){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(7),dp(14),dp(7));row.setMinimumHeight(dp(64));TextView a=text(main,14,TEXT);a.setMaxLines(2);a.setEllipsize(android.text.TextUtils.TruncateAt.END);TextView b=text(sub,11,MUTED);b.setMaxLines(2);b.setEllipsize(android.text.TextUtils.TruncateAt.END);row.addView(a,new LinearLayout.LayoutParams(-1,-2));if(sub!=null&&!sub.isEmpty())row.addView(b,new LinearLayout.LayoutParams(-1,-2));row.setClickable(true);row.setFocusable(true);row.setBackground(ripple(new ColorDrawable(Color.TRANSPARENT)));row.setOnClickListener(v->action.run());return row;}

  List<String> fetchBingSuggestions(String query){ArrayList<String> out=new ArrayList<>();HttpURLConnection c=null;try{String url="https://www.bing.com/osjson.aspx?query="+URLEncoder.encode(query,"UTF-8");c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(2500);c.setReadTimeout(3500);c.setRequestProperty("User-Agent","Mozilla/5.0");String body=read(c);JSONArray root=new JSONArray(body),values=root.optJSONArray(1);if(values!=null)for(int i=0;i<values.length()&&out.size()<8;i++){String s=values.optString(i).trim();if(!s.isEmpty())out.add(s);}}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}return out;}
  String read(HttpURLConnection c)throws Exception{try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];for(int n;(n=in.read(b))>0&&out.size()<256*1024;)out.write(b,0,n);return out.toString("UTF-8");}}
      void cancelSuggestionIndex(){hideSuggestions();if(address!=null){address.clearFocus();setAddress(currentUrl,false);}}
  void hideSuggestions(){final int closing=++suggestionGeneration;if(suggestionInput!=null){suggestionInput.clearFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(suggestionInput.getWindowToken(),0);}if(suggestionLayer.getVisibility()!=View.VISIBLE){suggestionLayer.removeAllViews();suggestionInput=null;suggestionResults=null;return;}suggestionLayer.animate().cancel();Runnable finish=()->{if(closing!=suggestionGeneration)return;suggestionLayer.removeAllViews();suggestionLayer.setVisibility(View.GONE);suggestionLayer.setAlpha(1f);suggestionLayer.setTranslationY(0f);suggestionInput=null;suggestionResults=null;};if(!motionEnabled()){finish.run();return;}suggestionLayer.animate().alpha(0f).translationY(dp(18)).setDuration(150).withEndAction(finish).start();}


  boolean handleNavigation(WebView view,String raw){String value=raw==null?"":raw.trim();if(value.isEmpty())return false;Uri uri;try{uri=Uri.parse(value);}catch(Exception ignored){return false;}String scheme=uri.getScheme();if(scheme==null||scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https"))return false;if(scheme.equalsIgnoreCase("intent")){Intent external;try{external=Intent.parseUri(value,Intent.URI_INTENT_SCHEME);}catch(Exception error){notice("无法解析应用跳转",false);return true;}String fallback=webFallback(external);sanitizeExternalIntent(external);confirmExternal(external,fallback);return true;}Intent external=new Intent(Intent.ACTION_VIEW,uri);external.addCategory(Intent.CATEGORY_BROWSABLE);external.setFlags(0);confirmExternal(external,nestedWebUrl(uri));return true;}
  void confirmExternal(Intent external,String fallback){String label=external.getData()==null?"外部应用":external.getData().toString();LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(20),dp(12),dp(20),dp(8));TextView note=text("网页请求打开外部应用：\n"+label,13,TEXT);note.setMaxLines(4);panel.addView(note,new LinearLayout.LayoutParams(-1,-2));AlertDialog d=new AlertDialog.Builder(this).setTitle("是否离开内置网页？").setView(panel).setNegativeButton("取消",null).setNeutralButton(fallback==null||fallback.isEmpty()?"留在网页":"打开网页备用链接",(x,w)->{if(fallback!=null&&!fallback.isEmpty())web.loadUrl(fallback);}).setPositiveButton("允许打开",(x,w)->{try{startActivity(external);}catch(Exception error){if(fallback!=null&&!fallback.isEmpty())web.loadUrl(fallback);else notice("未找到可处理此跳转的应用",true);}}).create();showRounded(d);}
  void sanitizeExternalIntent(Intent intent){intent.setAction(Intent.ACTION_VIEW);intent.addCategory(Intent.CATEGORY_BROWSABLE);intent.setComponent(null);intent.setSelector(null);intent.setFlags(0);intent.removeExtra("browser_fallback_url");}
  String webFallback(Intent intent){String fallback=intent==null?"":safeWebUrl(intent.getStringExtra("browser_fallback_url"));if(!fallback.isEmpty())return fallback;return intent==null?"":nestedWebUrl(intent.getData());}
  String nestedWebUrl(Uri uri){if(uri==null)return"";try{for(String name:uri.getQueryParameterNames()){String candidate=safeWebUrl(uri.getQueryParameter(name));if(!candidate.isEmpty())return candidate;}}catch(Exception ignored){}return"";}
  String safeWebUrl(String raw){if(raw==null)return"";String value=raw.trim();try{Uri uri=Uri.parse(value);String scheme=uri.getScheme();return scheme!=null&&(scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https"))?value:"";}catch(Exception ignored){return"";}}

    boolean isSearchInput(String raw){String v=raw==null?"":raw.trim();if(v.isEmpty())return false;try{Uri parsed=Uri.parse(v);String scheme=parsed.getScheme();if(scheme!=null&&(scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https")))return false;}catch(Exception ignored){}return v.contains(" ")||!v.matches("(?i)(?:localhost|(?:[a-z0-9-]+\\.)+[a-z]{2,})(?:[:/].*)?");}
  void saveSearchQuery(String raw){String value=raw==null?"":raw.trim();if(value.isEmpty())return;searchQueries.removeIf(x->x.equalsIgnoreCase(value));searchQueries.add(0,value);while(searchQueries.size()>MAX_SEARCH_HISTORY)searchQueries.remove(searchQueries.size()-1);saveState();}
  void navigateInput(String raw){String value=raw==null?"":raw.trim();if(isSearchInput(value))saveSearchQuery(value);hideSuggestions();address.clearFocus();String target=resolveInput(value);load(target);}

  String resolveInput(String raw){String v=raw==null?"":raw.trim();if(v.isEmpty())return"https://www.bing.com/";try{Uri parsed=Uri.parse(v);String scheme=parsed.getScheme();if(scheme!=null&&(scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https")))return v;}catch(Exception ignored){}if(!v.contains(" ")&&v.matches("(?i)(?:localhost|(?:[a-z0-9-]+\\.)+[a-z]{2,})(?:[:/].*)?"))return"https://"+v;try{return"https://www.bing.com/search?q="+URLEncoder.encode(v,"UTF-8");}catch(Exception ignored){return"https://www.bing.com/";}}
  void load(String raw){String u=resolveInput(raw);currentUrl=u;setAddress(u,false);web.loadUrl(u);}
  void setAddress(String value,boolean select){if(address==null||address.hasFocus())return;address.setText(value==null?"":value);if(select)address.selectAll();else address.setSelection(address.length());}
    static String cleanTitle(String value,String fallback){String v=value==null?"":value.trim();return v.isEmpty()?fallback:v;}
    String verificationCheckScript(){return"(function(){var h=document.documentElement?String(document.documentElement.innerHTML):'';var l=h.toLowerCase();var blocked=l.indexOf('aliyun_waf')>=0||l.indexOf('captchav2')>=0||h.indexOf('请完成以下操作，验证您是真人')>=0||l.indexOf('verify that you are a real person')>=0||l.indexOf('nc_1_n1z')>=0||l.indexOf('nocaptcha')>=0||(l.indexOf('slider')>=0&&(l.indexOf('captcha')>=0||l.indexOf('waf')>=0||l.indexOf('verify')>=0));return !blocked;})()";}
  void checkVerificationCompletion(boolean userInitiated){if(!challengeMode||verificationFinishing||web==null)return;web.evaluateJavascript(verificationCheckScript(),value->{if("true".equalsIgnoreCase(value))finishVerification();else if(userInitiated)notice("验证仍未完成，请先完成页面中的滑动验证",false);});}
  void maybeFinishVerificationAfterPage(){if(!challengeMode||verificationFinishing||web==null)return;final String loaded=currentUrl;web.postDelayed(()->{if(!challengeMode||verificationFinishing||web==null||!Objects.equals(loaded,currentUrl))return;checkVerificationCompletion(false);},650);}

    boolean isLanzouVerificationUrl(String raw){try{Uri uri=Uri.parse(raw==null?"":raw.trim());String scheme=uri.getScheme(),host=uri.getHost();return scheme!=null&&(scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https"))&&host!=null&&host.matches("(?i)(?:[a-z0-9-]+[.])*(?:lanzou[a-z0-9-]*|lanzov)[.]com");}catch(Exception ignored){return false;}}
  String verificationTarget(){String entered=getIntent()==null?"":getIntent().getStringExtra(EXTRA_URL);if(isLanzouVerificationUrl(currentUrl))return currentUrl;return entered==null?"":entered;}
  void finishVerification(){if(!challengeMode||verificationFinishing)return;String target=verificationTarget();String cookie="";try{android.webkit.CookieManager.getInstance().flush();cookie=android.webkit.CookieManager.getInstance().getCookie(target);}catch(Exception ignored){}if(cookie==null||cookie.trim().isEmpty()){notice("尚未检测到验证会话，请先完成滑动验证",false);return;}verificationFinishing=true;Intent result=new Intent().putExtra(EXTRA_VERIFICATION_URL,target).putExtra(EXTRA_VERIFICATION_COOKIE,cookie.trim());setResult(RESULT_OK,result);finish();}



  void showHitMenu(){WebView.HitTestResult hit=web.getHitTestResult();int type=hit==null?WebView.HitTestResult.UNKNOWN_TYPE:hit.getType();String extra=hit==null?"":hit.getExtra();ArrayList<Action> actions=new ArrayList<>();if(extra!=null&&!extra.isEmpty()&&(type==WebView.HitTestResult.SRC_ANCHOR_TYPE||type==WebView.HitTestResult.SRC_IMAGE_ANCHOR_TYPE||type==WebView.HitTestResult.ANCHOR_TYPE)){String link=extra;actions.add(new Action("打开链接",()->load(link)));actions.add(new Action("复制链接",()->copy("网页链接",link)));}if(extra!=null&&!extra.isEmpty()&&(type==WebView.HitTestResult.IMAGE_TYPE||type==WebView.HitTestResult.SRC_IMAGE_ANCHOR_TYPE)){String image=extra;actions.add(new Action("保存图片",()->saveImage(image)));actions.add(new Action("复制图片链接",()->copy("图片链接",image)));}actions.add(new Action("复制文本",this::copySelectedText));actions.add(new Action("分享当前页",()->share(currentUrl)));showContext(actions);}
  void showContext(List<Action> actions){contextLayer.removeAllViews();contextLayer.setVisibility(View.VISIBLE);contextLayer.setClickable(true);contextLayer.setOnClickListener(v->hideContext());LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(6),dp(6),dp(6),dp(6));card.setBackground(shape(SURFACE,18));card.setElevation(dp(12));for(Action a:actions){TextView row=menuRow(a.label);row.setOnClickListener(v->{a.run.run();hideContext();});card.addView(row,new LinearLayout.LayoutParams(dp(220),dp(46)));}int w=dp(232);int h=Math.max(dp(220),actions.size()*dp(46)+dp(12));int x=Math.max(dp(8),Math.min((int)lastTouchX-w/2,getResources().getDisplayMetrics().widthPixels-w-dp(8)));int y=Math.max(dp(64),Math.min((int)lastTouchY-dp(24),getResources().getDisplayMetrics().heightPixels-h-dp(8)));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(w,-2,Gravity.TOP|Gravity.START);p.leftMargin=x;p.topMargin=y;contextLayer.addView(card,p);card.setClickable(true);card.setOnClickListener(v->{});contextLayer.setAlpha(0f);contextLayer.animate().alpha(1f).setDuration(140).start();}
  void hideContext(){if(contextLayer.getVisibility()!=View.VISIBLE)return;contextLayer.animate().alpha(0f).setDuration(130).withEndAction(()->{contextLayer.removeAllViews();contextLayer.setVisibility(View.GONE);contextLayer.setAlpha(1f);}).start();}
  void copySelectedText(){web.evaluateJavascript("(function(){return String(window.getSelection?window.getSelection().toString():'')})()",value->{String s=value==null?"":value;try{s=new JSONArray("["+s+"]").optString(0);}catch(Exception ignored){}if(s.trim().isEmpty())notice("没有选中的文本",false);else copy("网页文本",s);});}
  void saveImage(String url){String name=URLUtil.guessFileName(url,null,null);if(MainActivity.enqueueWebDownload(url,name))notice("已加入图片下载："+name,false);else notice("主页面暂不可用，无法保存图片",true);}
  void copy(String label,String value){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(label,value));notice("已复制",false);}
  void share(String value){try{startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,value),"分享网页"));}catch(Exception error){notice("没有可用的分享应用",true);}}

  void menu(View anchor){if(menuPopup!=null&&menuPopup.isShowing()){menuPopup.dismiss();return;}String[] labels={"刷新","前进","下载历史","系统浏览器打开","复制链接","分享链接"};LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(5),dp(5),dp(5),dp(5));panel.setBackground(menuShape());panel.setElevation(dp(10));for(int i=0;i<labels.length;i++){final int which=i;TextView row=menuRow(labels[i]);row.setOnClickListener(v->{if(menuPopup!=null)menuPopup.dismiss();switch(which){case 0:web.reload();break;case 1:if(web.canGoForward())web.goForward();break;case 2:if(!MainActivity.showWebDownloadHistoryDialog(this))notice("正在打开下载历史",false);break;case 3:try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(currentUrl)));}catch(Exception e){notice("无法打开系统浏览器",true);}break;case 4:copy("网页链接",currentUrl);break;default:share(currentUrl);}});panel.addView(row,new LinearLayout.LayoutParams(dp(188),dp(45)));}menuPopup=new PopupWindow(panel,dp(198),WindowManager.LayoutParams.WRAP_CONTENT,true);menuPopup.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));menuPopup.setOutsideTouchable(true);menuPopup.setElevation(dp(8));menuPopup.showAsDropDown(anchor,0,0,Gravity.END);panel.setAlpha(0f);panel.setTranslationY(-dp(8));panel.animate().alpha(1f).translationY(0).setDuration(130).start();}
    GradientDrawable menuShape(){GradientDrawable g=new GradientDrawable();g.setColor(SURFACE);g.setCornerRadius(0f);return g;}
  GradientDrawable topRounded(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadii(new float[]{dp(radius),dp(radius),dp(radius),dp(radius),0,0,0,0});g.setStroke(dp(1),DIV);return g;}
  GradientDrawable bottomRounded(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadii(new float[]{0,0,0,0,dp(radius),dp(radius),dp(radius),dp(radius)});g.setStroke(dp(1),DIV);return g;}

  void favoriteCurrent(){if(currentUrl.isEmpty())return;Entry e=new Entry(cleanTitle(currentTitle,currentUrl),currentUrl,System.currentTimeMillis());upsert(favorites,e);saveState();notice("已加入收藏，并打开路径选择",false);MainActivity.favoriteWebPage(this,currentUrl,e.title);}
  void showHistoryDialog(){if(history.isEmpty()){notice("暂无浏览历史",false);return;}final LinkedHashSet<String> selected=new LinkedHashSet<>();LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(list);panel.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);Button favorite=new Button(this),remove=new Button(this);favorite.setText("加入收藏");remove.setText("删除");actions.addView(favorite,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(remove,new LinearLayout.LayoutParams(0,dp(48),1));panel.addView(actions,new LinearLayout.LayoutParams(-1,dp(48)));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("浏览历史").setView(panel).setNegativeButton("关闭",null).create();final Runnable[] refresh={null};refresh[0]=()->{list.removeAllViews();for(Entry e:new ArrayList<>(history)){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(4),dp(8),dp(4));CheckBox box=new CheckBox(this);box.setClickable(false);box.setChecked(selected.contains(e.url));box.setVisibility(selected.isEmpty()?View.GONE:View.VISIBLE);row.addView(box,new LinearLayout.LayoutParams(dp(38),dp(58)));ImageView icon=new ImageView(this);icon.setImageResource(android.R.drawable.ic_menu_recent_history);row.addView(icon,new LinearLayout.LayoutParams(dp(34),dp(34)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(8),0,0,0);TextView name=text(e.title,13,TEXT);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);TextView url=text(e.url,10,MUTED);url.setSingleLine(true);url.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);words.addView(name,new LinearLayout.LayoutParams(-1,dp(28)));words.addView(url,new LinearLayout.LayoutParams(-1,dp(24)));row.addView(words,new LinearLayout.LayoutParams(0,dp(58),1));row.setOnClickListener(v->{if(selected.isEmpty()){dialog.dismiss();load(e.url);}else{if(!selected.add(e.url))selected.remove(e.url);refresh[0].run();}});row.setOnLongClickListener(v->{selected.add(e.url);refresh[0].run();return true;});list.addView(row,new LinearLayout.LayoutParams(-1,dp(64)));}};favorite.setOnClickListener(v->{for(Entry e:new ArrayList<>(history))if(selected.contains(e.url))upsert(favorites,e);saveState();selected.clear();refresh[0].run();notice("已加入收藏",false);});remove.setOnClickListener(v->{history.removeIf(e->selected.contains(e.url));saveState();selected.clear();refresh[0].run();});dialog.setOnShowListener(x->{Window w=dialog.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));View decor=w.getDecorView();decor.setBackground(shape(SURFACE,20));}refresh[0].run();});showRounded(dialog);}
  void pushHistory(String title,String url){if(url==null||url.isEmpty()||url.startsWith("about:"))return;history.removeIf(e->e.url.equals(url));history.add(0,new Entry(title,url,System.currentTimeMillis()));while(history.size()>MAX_HISTORY)history.remove(history.size()-1);saveState();}
  void upsert(List<Entry> list,Entry e){list.removeIf(x->x.url.equals(e.url));list.add(0,e);while(list.size()>MAX_HISTORY)list.remove(list.size()-1);}
    void loadState(){history.clear();favorites.clear();searchQueries.clear();android.content.SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);readEntries(p.getString(HISTORY,"[]"),history);readEntries(p.getString(FAVORITES,"[]"),favorites);readQueries(p.getString(SEARCH_HISTORY,"[]"),searchQueries);}

    void saveState(){getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString(HISTORY,writeEntries(history)).putString(FAVORITES,writeEntries(favorites)).putString(SEARCH_HISTORY,writeQueries(searchQueries)).apply();}

  void readEntries(String raw,List<Entry> out){try{JSONArray a=new JSONArray(raw);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String u=o.optString("u");if(!u.isEmpty())out.add(new Entry(o.optString("t",u),u,o.optLong("a")));}}catch(Exception ignored){}}
    String writeEntries(List<Entry> values){JSONArray a=new JSONArray();for(Entry e:values)try{a.put(new JSONObject().put("t",e.title).put("u",e.url).put("a",e.at));}catch(Exception ignored){}return a.toString();}
  void readQueries(String raw,List<String> out){try{JSONArray a=new JSONArray(raw);for(int i=0;i<a.length()&&out.size()<MAX_SEARCH_HISTORY;i++){String value=a.optString(i).trim();if(!value.isEmpty()&&!out.contains(value))out.add(value);}}catch(Exception ignored){}}
  String writeQueries(List<String> values){JSONArray a=new JSONArray();for(int i=0;i<Math.min(MAX_SEARCH_HISTORY,values.size());i++)a.put(values.get(i));return a.toString();}


  void download(String u,String d,String m,long z){String name=fileName(u,d,m);notice("已加入下载："+name,false);if(MainActivity.enqueueWebDownload(u,name))return;Intent i=new Intent(this,MainActivity.class).setAction(MainActivity.ACTION_WEB_DOWNLOAD).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);i.putExtra("url",u);i.putExtra("name",name);startActivity(i);}
  String fileName(String u,String d,String m){String name=contentDispositionName(d);if(name.isEmpty())name=URLUtil.guessFileName(u,d,m);name=cleanFileName(name.isEmpty()?"download":name);String mime=m==null?"":m.split(";",2)[0].trim().toLowerCase(java.util.Locale.ROOT),wanted=MainActivity.extensionForMime(mime),current=MainActivity.fileNameExtension(name);if(!wanted.isEmpty()&&(current.isEmpty()||current.equals("bin")||current.equals("dat")||current.equals("tmp")))name=MainActivity.replaceOrAppendExtension(name,wanted);return name;}
  String contentDispositionName(String d){if(d==null)return"";String value=d.trim();Matcher star=Pattern.compile("(?i)filename[*][ \\t]*=[ \\t]*(?:UTF-8''|utf-8'')?([^;]+)").matcher(value);if(star.find())return decodeName(star.group(1));Matcher normal=Pattern.compile("(?i)filename[ \\t]*=[ \\t]*(?:\"([^\"]+)\"|([^;]+))").matcher(value);if(normal.find())return decodeName(normal.group(1)!=null?normal.group(1):normal.group(2));return"";}
  String decodeName(String raw){try{return URLDecoder.decode(raw.replaceAll("^[\"']|[\"']$","").trim(),"UTF-8");}catch(Exception ignored){return raw==null?"":raw.trim();}}
  String cleanFileName(String raw){String value=raw==null?"":raw.trim();value=value.replaceAll("[\\\\/:*?\"<>|\\r\\n]+","_");return value.isEmpty()?"download":value;}

  void applyPalette(){int mode=getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK;boolean dark=mode==android.content.res.Configuration.UI_MODE_NIGHT_YES;BG=dark?Color.rgb(19,18,22):Color.rgb(255,251,255);SURFACE=dark?Color.rgb(32,31,36):Color.WHITE;TEXT=dark?Color.rgb(232,225,229):Color.rgb(29,27,32);MUTED=dark?Color.rgb(202,196,208):Color.rgb(98,91,113);DIV=dark?Color.rgb(73,69,79):Color.rgb(230,224,233);PRIMARY=dark?Color.rgb(208,188,255):Color.rgb(103,80,164);}
  TextView tool(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(sp);v.setGravity(Gravity.CENTER);v.setClickable(true);v.setFocusable(true);v.setBackground(ripple(new ColorDrawable(Color.TRANSPARENT)));return v;}
  TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextColor(color);v.setTextSize(sp);v.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);return v;}
  TextView menuRow(String label){TextView row=new TextView(this);row.setText(label);row.setTextColor(TEXT);row.setTextSize(14);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),0,dp(14),0);row.setClickable(true);row.setFocusable(true);row.setBackground(ripple(new ColorDrawable(Color.TRANSPARENT)));return row;}
  void notice(String message,boolean longLived){TextView label=new TextView(this);label.setText(message);label.setTextColor(TEXT);label.setTextSize(12);label.setGravity(Gravity.CENTER_VERTICAL);label.setPadding(dp(14),0,dp(14),0);label.setSingleLine(false);label.setMaxLines(2);label.setBackground(shape(SURFACE,16));label.setElevation(dp(8));int noticeWidth=Math.min(dp(320),Math.max(dp(220),getResources().getDisplayMetrics().widthPixels-dp(24)));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(noticeWidth,dp(52),Gravity.TOP|Gravity.END);lp.setMargins(dp(12),dp(72),dp(12),0);noticeLayer.addView(label,lp);label.setAlpha(0f);label.setTranslationY(dp(36));label.animate().alpha(1f).translationY(0).setDuration(160).withEndAction(()->label.postDelayed(()->label.animate().alpha(0f).translationY(dp(36)).setDuration(180).withEndAction(()->noticeLayer.removeView(label)).start(),longLived?5000:2600)).start();}
    void showRounded(AlertDialog dialog){dialog.show();Window w=dialog.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.getDecorView().setBackground(shape(SURFACE,20));}}
  Drawable ripple(Drawable content){if(Build.VERSION.SDK_INT>=21)return new RippleDrawable(android.content.res.ColorStateList.valueOf(DIV),content,null);return content;}
  GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    void handleBack(){if(contextLayer!=null&&contextLayer.getVisibility()==View.VISIBLE){hideContext();return;}if(suggestionLayer!=null&&suggestionLayer.getVisibility()==View.VISIBLE){cancelSuggestionIndex();return;}if(web!=null&&web.canGoBack())web.goBack();else finish();}

  @SuppressLint("GestureBackNavigation") public void onBackPressed(){handleBack();}
  @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==FILE_PICK){ValueCallback<Uri[]> callback=fileCallback;fileCallback=null;if(callback!=null)callback.onReceiveValue(resultCode==RESULT_OK?WebChromeClient.FileChooserParams.parseResult(resultCode,data):null);}}
  @Override protected void onDestroy(){if(fileCallback!=null)fileCallback.onReceiveValue(null);webIo.shutdownNow();if(web!=null){web.stopLoading();web.destroy();}super.onDestroy();}
  int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
  static final class Entry{final String title,url;final long at;Entry(String t,String u,long a){title=t==null?"":t;url=u==null?"":u;at=a;}}
  static final class Action{final String label;final Runnable run;Action(String l,Runnable r){label=l;run=r;}}
}