package cc.nkbr.lanzouplus;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.annotation.SuppressLint;import android.view.*;import android.webkit.*;import android.widget.*;import android.window.*;import java.net.*;import java.util.regex.*;

public final class LanzouWebActivity extends Activity{
  static final String EXTRA_URL="u";WebView web;TextView address;FrameLayout shell,noticeLayer;PopupWindow menuPopup;String currentUrl="";int BG,SURFACE,TEXT,MUTED,DIV,PRIMARY;
  public void onCreate(Bundle b){super.onCreate(b);applyPalette();if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);shell=new FrameLayout(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);shell.addView(root,new FrameLayout.LayoutParams(-1,-1));noticeLayer=new FrameLayout(this);FrameLayout.LayoutParams notices=new FrameLayout.LayoutParams(-1,-1);shell.addView(noticeLayer,notices);if(Build.VERSION.SDK_INT>=20)shell.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(0,insets.getSystemWindowInsetTop(),0,0);return insets;});
    LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),dp(6),dp(8),dp(6));bar.setBackgroundColor(SURFACE);LinearLayout capsule=new LinearLayout(this);capsule.setGravity(Gravity.CENTER_VERTICAL);capsule.setPadding(dp(2),0,dp(2),0);GradientDrawable cap=shape(Color.TRANSPARENT,24);cap.setStroke(dp(1),DIV);capsule.setBackground(cap);capsule.setClipToOutline(true);TextView back=tool("‹",26);back.setOnClickListener(v->handleBack());capsule.addView(back,new LinearLayout.LayoutParams(dp(44),dp(42)));address=new TextView(this);address.setTextColor(TEXT);address.setTextSize(13);address.setSingleLine(true);address.setGravity(Gravity.CENTER_VERTICAL);address.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);address.setPadding(dp(8),0,dp(8),0);capsule.addView(address,new LinearLayout.LayoutParams(0,dp(42),1));TextView menu=tool("⋮",24);menu.setOnClickListener(v->menu(menu));capsule.addView(menu,new LinearLayout.LayoutParams(dp(44),dp(42)));bar.addView(capsule,new LinearLayout.LayoutParams(-1,dp(44)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(56)));
    web=new WebView(this);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return handleNavigation(v,u);}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return r!=null&&r.isForMainFrame()&&handleNavigation(v,r.getUrl()==null?"":r.getUrl().toString());}public void onPageFinished(WebView v,String u){currentUrl=u==null?"":u;address.setText(currentUrl);}});web.setDownloadListener((u,ua,d,m,z)->download(u,d,m,z));root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(shell);load(getIntent().getStringExtra(EXTRA_URL));}
    boolean handleNavigation(WebView view,String raw){String value=raw==null?"":raw.trim();if(value.isEmpty())return false;Uri uri;try{uri=Uri.parse(value);}catch(Exception ignored){return false;}String scheme=uri.getScheme();if(scheme==null||scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https"))return false;if(scheme.equalsIgnoreCase("intent")){Intent external;try{external=Intent.parseUri(value,Intent.URI_INTENT_SCHEME);}catch(Exception error){notice("无法解析应用跳转",false);return true;}String fallback=webFallback(external);sanitizeExternalIntent(external);try{startActivity(external);}catch(ActivityNotFoundException|SecurityException error){if(!fallback.isEmpty())view.loadUrl(fallback);else notice("未找到可处理此跳转的应用",false);}return true;}Intent external=new Intent(Intent.ACTION_VIEW,uri);external.addCategory(Intent.CATEGORY_BROWSABLE);external.setFlags(0);try{startActivity(external);}catch(ActivityNotFoundException|SecurityException error){String fallback=nestedWebUrl(uri);if(!fallback.isEmpty())view.loadUrl(fallback);else notice("未找到可处理此跳转的应用",false);}return true;}
  void sanitizeExternalIntent(Intent intent){intent.setAction(Intent.ACTION_VIEW);intent.addCategory(Intent.CATEGORY_BROWSABLE);intent.setComponent(null);intent.setSelector(null);intent.setFlags(0);intent.removeExtra("browser_fallback_url");}
  String webFallback(Intent intent){String fallback=intent==null?"":safeWebUrl(intent.getStringExtra("browser_fallback_url"));if(!fallback.isEmpty())return fallback;return intent==null?"":nestedWebUrl(intent.getData());}
  String nestedWebUrl(Uri uri){if(uri==null)return"";try{for(String name:uri.getQueryParameterNames()){String candidate=safeWebUrl(uri.getQueryParameter(name));if(!candidate.isEmpty())return candidate;}}catch(Exception ignored){}return"";}
  String safeWebUrl(String raw){if(raw==null)return"";String value=raw.trim();try{Uri uri=Uri.parse(value);String scheme=uri.getScheme();return scheme!=null&&(scheme.equalsIgnoreCase("http")||scheme.equalsIgnoreCase("https"))?value:"";}catch(Exception ignored){return"";}}
  void applyPalette(){int mode=getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK;boolean dark=mode==android.content.res.Configuration.UI_MODE_NIGHT_YES;BG=dark?Color.rgb(19,18,22):Color.rgb(255,251,255);SURFACE=dark?Color.rgb(32,31,36):Color.WHITE;TEXT=dark?Color.rgb(232,225,229):Color.rgb(29,27,32);MUTED=dark?Color.rgb(202,196,208):Color.rgb(98,91,113);DIV=dark?Color.rgb(73,69,79):Color.rgb(230,224,233);PRIMARY=dark?Color.rgb(208,188,255):Color.rgb(103,80,164);}
  TextView tool(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(sp);v.setGravity(Gravity.CENTER);v.setClickable(true);v.setFocusable(true);v.setBackground(ripple(new ColorDrawable(Color.TRANSPARENT)));return v;}
  void load(String raw){String u=norm(raw);currentUrl=u;address.setText(u);web.loadUrl(u);}String norm(String v){v=v==null?"":v.trim();if(v.isEmpty())return"https://wwc.lanzoux.com/";return v.startsWith("http")?v:"https://"+v;}
  void menu(View anchor){if(menuPopup!=null&&menuPopup.isShowing()){menuPopup.dismiss();return;}String[] labels={"下载历史","系统浏览器打开","复制链接","分享链接"};LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(6),dp(6),dp(6),dp(6));panel.setBackground(shape(SURFACE,18));panel.setElevation(dp(10));for(int i=0;i<labels.length;i++){final int which=i;TextView row=menuRow(labels[i]);row.setOnClickListener(v->{if(menuPopup!=null)menuPopup.dismiss();if(which==0){MainActivity.showWebDownloadHistoryDialog(this);}else if(which==1)startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(currentUrl)));else if(which==2){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("网页链接",currentUrl));notice("链接已复制",false);}else startActivity(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,currentUrl));});panel.addView(row,new LinearLayout.LayoutParams(dp(188),dp(46)));}menuPopup=new PopupWindow(panel,dp(200),WindowManager.LayoutParams.WRAP_CONTENT,true);menuPopup.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));menuPopup.setOutsideTouchable(true);if(Build.VERSION.SDK_INT>=21)menuPopup.setElevation(dp(8));menuPopup.showAsDropDown(anchor,-dp(158),dp(6));if(Build.VERSION.SDK_INT>=12){panel.setAlpha(0f);panel.setTranslationY(-dp(10));panel.animate().alpha(1f).translationY(0).setDuration(160).start();}}
  TextView menuRow(String label){TextView row=new TextView(this);row.setText(label);row.setTextColor(TEXT);row.setTextSize(14);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),0,dp(14),0);row.setClickable(true);row.setFocusable(true);row.setBackground(ripple(new ColorDrawable(Color.TRANSPARENT)));return row;}
  
  void download(String u,String d,String m,long z){String name=fileName(u,d,m);notice("已加入下载："+name,false);if(MainActivity.enqueueWebDownload(u,name))return;Intent i=new Intent(this,MainActivity.class).setAction(MainActivity.ACTION_WEB_DOWNLOAD).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);i.putExtra("url",u);i.putExtra("name",name);startActivity(i);}
  String fileName(String u,String d,String m){String name=contentDispositionName(d);if(name.isEmpty())name=URLUtil.guessFileName(u,d,m);return cleanFileName(name.isEmpty()?"download":name);}
  String contentDispositionName(String d){if(d==null)return"";String value=d.trim();Matcher star=Pattern.compile("(?i)filename[*][ \t]*=[ \t]*(?:UTF-8''|utf-8'')?([^;]+)").matcher(value);if(star.find())return decodeName(star.group(1));Matcher normal=Pattern.compile("(?i)filename[ \t]*=[ \t]*(?:\"([^\"]+)\"|([^;]+))").matcher(value);if(normal.find())return decodeName(normal.group(1)!=null?normal.group(1):normal.group(2));return"";}
  String decodeName(String raw){try{return URLDecoder.decode(raw.replaceAll("^[\"']|[\"']$","").trim(),"UTF-8");}catch(Exception ignored){return raw==null?"":raw.trim();}}
  String cleanFileName(String raw){String value=raw==null?"":raw.trim();value=value.replaceAll("[\\/:*?\"<>|\r\n]+","_");return value.isEmpty()?"download":value;}
  void notice(String message,boolean longLived){TextView label=new TextView(this);label.setText(message);label.setTextColor(TEXT);label.setTextSize(12);label.setGravity(Gravity.CENTER_VERTICAL);label.setPadding(dp(14),0,dp(14),0);label.setSingleLine(false);label.setMaxLines(2);label.setBackground(shape(SURFACE,16));label.setElevation(dp(8));int noticeWidth=Math.min(dp(320),Math.max(dp(220),getResources().getDisplayMetrics().widthPixels-dp(24)));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(noticeWidth,dp(52),Gravity.TOP|Gravity.END);lp.setMargins(dp(12),dp(72),dp(12),0);noticeLayer.addView(label,lp);label.setAlpha(0f);label.setTranslationY(dp(36));label.animate().alpha(1f).translationY(0).setDuration(160).withEndAction(()->label.postDelayed(()->label.animate().alpha(0f).translationY(dp(36)).setDuration(180).withEndAction(()->noticeLayer.removeView(label)).start(),longLived?5000:2600)).start();}
  Drawable ripple(Drawable content){if(Build.VERSION.SDK_INT>=21)return new RippleDrawable(android.content.res.ColorStateList.valueOf(DIV),content,null);return content;}
  GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
  void handleBack(){if(web!=null&&web.canGoBack())web.goBack();else finish();}
  @SuppressLint("GestureBackNavigation") public void onBackPressed(){handleBack();}
  int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} }
