package cc.nkbr.lanzouplus;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.annotation.SuppressLint;import android.view.*;import android.webkit.*;import android.widget.*;import android.window.*;

public final class LanzouWebActivity extends Activity{
  static final String EXTRA_URL="u";WebView web;TextView address;String currentUrl="";
  public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);if(Build.VERSION.SDK_INT>=20)root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(0,insets.getSystemWindowInsetTop(),0,0);return insets;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView back=tool("‹");back.setOnClickListener(v->handleBack());bar.addView(back,new LinearLayout.LayoutParams(dp(44),dp(44)));address=new TextView(this);bar.addView(address,new LinearLayout.LayoutParams(0,dp(44),1));TextView menu=tool("⋮");menu.setOnClickListener(v->menu());bar.addView(menu,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(52)));web=new WebView(this);web.getSettings().setJavaScriptEnabled(true);web.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){currentUrl=u==null?"":u;address.setText(currentUrl);}});web.setDownloadListener((u,ua,d,m,z)->download(u,d,m,z));root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load(getIntent().getStringExtra(EXTRA_URL));}
  TextView tool(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(28);v.setGravity(Gravity.CENTER);v.setClickable(true);return v;}
  void load(String raw){String u=norm(raw);currentUrl=u;address.setText(u);web.loadUrl(u);}String norm(String v){v=v==null?"":v.trim();if(v.isEmpty())return"https://www.lanzouw.com/";return v.startsWith("http")?v:"https://"+v;}
  void menu(){new AlertDialog.Builder(this).setItems(new String[]{"下载历史","浏览器打开","复制链接","分享链接"},(d,w)->{if(w==0)startActivity(new Intent(this,MainActivity.class).setAction(MainActivity.ACTION_OPEN_DOWNLOADS).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));else if(w==1)startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(currentUrl)));else if(w==2)((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("网页链接",currentUrl));else startActivity(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,currentUrl));}).show();}
  void download(String u,String d,String m,long z){String name=URLUtil.guessFileName(u,d,m);if(MainActivity.enqueueWebDownload(u,name)){Toast.makeText(this,"已加入下载",Toast.LENGTH_SHORT).show();return;}Intent i=new Intent(this,MainActivity.class).setAction(MainActivity.ACTION_WEB_DOWNLOAD).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);i.putExtra("url",u);i.putExtra("name",name);startActivity(i);}
  void handleBack(){if(web!=null&&web.canGoBack())web.goBack();else finish();}
  @SuppressLint("GestureBackNavigation") public void onBackPressed(){handleBack();}
  int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} }
